spring:
    application:
        name: Fleet Status
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        url: jdbc:mysql://localhost:3306/dhl_fleetstatus
        username: admin
        password: P@$$w0rd2!
