spring:
    application:
        name: Fleet Status
    profiles:
        active: local
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    datasource:
        hikari:
            connection-timeout: 30000

server:
    error:
        whitelabel:
            enabled: false  # avoid Whitelabel Error Page
        path: /error       # path to customised error page
        include-message: always
