spring:
    application:
        name: Fleet Status
    profiles:
        active: dev
    jpa:
        hibernate:
            format_sql: true
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    datasource:
        hikari:
            connection-timeout: 30000
        # Azure DB connection
#        url: jdbc:sqlserver://dhlfleetstatus.database.windows.net;encrypt=true;trustServerCertificate=true;databaseName=dhl_fleetstatus
#        username: fleetstatus_admin
#        password: P@$$w0rd2!

        # Local DB connection for testing
        url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=dhl_fleetstatus
        username: sa
        password: password
    security:
        oauth2:
          client:
            registration:
                github:
                    client-id: Ov23liCYYuCyjrKsKybO
                    client-secret: 95562529098c66841ace12d9eac664d438f023de
                    scope: read:user
                    redirect-uri: "{baseUrl}/"
                    client-name: GitHub
            provider:
                github:
                    authorization-uri: https://github.com/login/oauth/authorize
                    token-uri: https://hithub.com/login/oauth/access_token
                    user-info-uri: https://api.github.com/user

server:
    error:
        whitelabel:
            enabled: false  # avoid Whitelabel Error Page
        path: /error       # path to customised error page
        include-message: always
