package com.fleet.status.dto;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Data;
import lombok.ToString;

import java.util.List;

@Entity
@Data
@Table(name = "TAircraft")
public class Aircraft {

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "intAircraftId")
    private Long aircraftId;

    @Column(name = "strTailNumber")
    private String tailNumber;
    @Column(name = "strNextUpdate")
    private String nextUpdate;
    @Column(name = "strRemark")
    private String remark;
    @Column(name = "blnBackInService")
    private Integer backInService;
    @Column(name = "dtmStartTime")
    private String startTime;
    @Column(name = "dtmEndTime")
    private String endTime;

    @ManyToOne
    @JoinColumn(name = "intCarrierId", referencedColumnName = "intCarrierId")
    private Carrier carrier;

    @ManyToMany
    @ToString.Exclude //avoid stackoverflow error when use toString method generated by @Data, they print each other between many to many
    @JoinTable(
            name = "TAircraft_Reason",
            joinColumns = @JoinColumn(name = "intAircraftId"),
            inverseJoinColumns = @JoinColumn(name = "intReasonId")
    )
    private List<Reason> reason;

    @Transient
    private String reasonString;
}
